# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('black_belt', '0002_auto_20161216_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
